// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntifxjarxgxmgoqgmtzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50aWZ4amFyeGd4bWdvcWdtdHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTczOTQsImV4cCI6MjA2OTg5MzM5NH0.i2JM8QGshO4RRkMmh-WMRw-Mr2Ta-4fKk0mwvCCl9EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});